CREATE TABLE Hospital_MedicalRecord (
recNo SMALLINT UNSIGNED,
patient CHAR(9),
doctor CHAR(9),
enteredOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
diagnosis MEDIUMTEXT NOT NULL,
treatment VARCHAR(1000),

PRIMARY KEY(recNo,patient),
CONSTRAINT FK_patient FOREIGN KEY (patient) REFERENCES Hospital_Patient(NINumber) ON DELETE CASCADE ON UPDATE RESTRICT,
CONSTRAINT FK_doctor FOREIGN KEY(doctor) REFERENCES Hospital_Doctor(NINumber) ON DELETE SET NULL ON UPDATE RESTRICT
);